name: cron_vercel

on:
    schedule:
        - cron: '0 */2 * * *' # Run every 2 hours.

jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - run: curl ${{ secrets.REBUILD_MASTER_HOOK }} # Vercel Github hook
