name: ci

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn lint

    cypress:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install

            - name: Get deployment URL
              id: deployment
              uses: dorshinar/get-deployment-url@master
              timeout-minutes: 5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Cypress
              uses: cypress-io/github-action@v2
              with:
                  config: baseUrl=${{ steps.deployment.outputs.deployment }}
